version: '3.7'

services:
  front-app:
    container_name: front-app
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: 'nginx'
    volumes:
      - ./nginx-balancer.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/private/key.pem
    ports:
      - "80:80"
      - "443:443"
    restart: always